name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.4]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        go build -o cloudflare-stream-downloader

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: cloudflare-stream-downloader-${{ matrix.os }}
        path: |
          cloudflare-stream-downloader
